#if !canImport(ObjectiveC)
import XCTest

extension CalculatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CalculatorTests = [
        ("testEvaluate", testEvaluate),
        ("testParse", testParse),
        ("testTokenize", testTokenize),
    ]
}

extension NodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NodeTests = [
        ("testAdd", testAdd),
        ("testFactorial", testFactorial),
        ("testLn", testLn),
        ("testLog", testLog),
        ("testModulusBracket", testModulusBracket),
        ("testSubtract", testSubtract),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testSuffixWhile", testSuffixWhile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CalculatorTests.__allTests__CalculatorTests),
        testCase(NodeTests.__allTests__NodeTests),
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
